FROM rust:1.37
RUN apt-get update \
    && apt-get install -y clang llvm-dev libclang-dev \
    && apt-get install -y libsqlite3-dev
RUN cargo install diesel_cli --no-default-features --features "sqlite"

WORKDIR /usr/src/api
COPY ./backend ./
COPY backend_start.sh ./

RUN chmod +x backend_start.sh
RUN cargo install --path /usr/src/api/

CMD ["./backend_start.sh"]
EXPOSE 9000/tcp
