FROM node:13 AS builder

WORKDIR /app
COPY ./frontend .
RUN npm install && npm run build --prod

FROM nginx:1.17
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/* /usr/share/nginx/html/
EXPOSE 80/tcp
